# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  host: DESKTOP-FQPDNGK\SQLEXPRESS
  adapter: sqlserver
  mode: odbc
  # dsn: DSN_Name
  username: sa
  password: 123456

development:
  <<: *default
  database: API

test:
  <<: *default
  database: API

production:
  <<: *default
  database: API